const AUTH_SUCCESS = "auth/AUTH_SUCCESS";
const AUTH_USER_SUCCESS = "auth/AUTH_USER_SUCCESS";
const AUTH_FAILED = "auth/AUTH_FAILED";
const AUTH_LOGOUT = "auth/AUTH_LOGOUT";
export default {
  AUTH_SUCCESS,
  AUTH_USER_SUCCESS,
  AUTH_FAILED,
  AUTH_LOGOUT,
};
