language: node_js
node_js:
- '10'
warnings_are_errors: false
script:
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: XJfQ5g/+jPu1acoGeg6ypjICCfZUHcKVmqAB073+5hK5xDPj6slTE5ilYCB/O2cTbOs/naGoAmPArRPEBJoth+pP4BIhn3Urblv740iscWcYGq+kTOuJFWYrE6MBLI+tHLBCNiR14fTRn42RFG7iXibve3jRdkBtSPsTZwarn3bzbMYk7G6gXNw/wV4HJw9D3nzq4zJX4zkzdCpcwvY9U+3q5kDX8hE54ay9kbKzI0kOikTUX/Qnd7nGUtQcSOCFAo6wHAAWzpTYYYdLiC6SoMLAjgAoqBcMaFF2/lER+j6LNj8QNmVPLmGoV9ebd8g4YUbspZfNDfJJwVuCT7rtqOS2OpqXRCy989VgyO+XgrD21LFQ65EOeRPdN7WW0jHaiEicX+uPI6ZXbdpXnIeIZHjj3iGqXFr3XyZJO8wbQcddQwUpinjXOH0+40QM/DfoORt/GBJbXkbIxyM2tQebYIafhpX52gfQigcqf1fg5fL3PK2s4GsIqZ+b6YmEb/hdPmnBGxXhPbZmFyTDc8RRsVzGnxCZM/p7OQVK0SgfgDpUmPCWl6dGBMXRY60YLUYP4WNEmPMrmh/EwsaDvHp4/KzPb7emmduUrMQrXdShum9c5ATAt+boaVTyZpat7bWzGg1fXioa/h3kWwMK533EVlR7Y8QFugKqKttGGyADo8Y=
