language: node_js
node_js:
- '10'
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: buxYYY+Vgk3sw8ocP91dy3annljKmfn0hjE54aAddo1JRO3ow/i02M7+ZE9sqamVMAHbVhwGstRDZKNYM/V67Tqwwz3jVF7niBjPrrkWBupbE+f2xvSEsK2wJBMSBujX97gn4g2xrQUiVV7051YdKtIIgkRlhinV06SBr7gY6Q8Hu3uvX082RSUrR4OYz83r/JaAXGR1FxATrRPVdVCksKj1M1njsSMRzqCYRdo/S80G4XvAJYUYLVtXzvCFPJMfZPxI3MgRhHmUnTotah3tFeD/Ua++bJC46mtWW8BKJPOjEhBjxcn78c6rYth7kdHKYBC+aGYhB70iqebbh7maMb3xriIpzCAXzo3pbf81cLhIlCfPsmWAFoqciSBrvqfozgEV3f1LMAUu6eHYdvFMPw95qVPyvchTb34WZniWloNQNv6V4aV/5tvL6SvfmH2rfg9DdF+CB6wh0OeF7JTWmsfiFCLRV/QJ7zyBq9tOxPPvgjWyv5CygmPfA6A9mqH9tph31QS0IK5LN1irKVTKUFwHSsl01zCU/rMB1/yKVlZd8YAs+vnKpvuL6SJor2ELRUT5+4A2Pjv5ypUFPliI1zrHiVHR8P5pab5N7oqJAK5vYy/M+xFOw0fmkO29BcoftRs+PdJFFSk1L/wPcAptWUSqnnGsOOifluNbZOeE0Vw=
env:
  global:
    secure: JpQTq3ag//TnFaMAEVRgwilNPcH91XIn+tsP/wTY0CtX/jLJpE1oycXzYr00ArtpY6GTjqymK+hhHKZaywcxhsXUH1EUrG1Opwf8/BufRXwmjRKosihuL0ni2jaAURXpYSfxkaJB9naIO0KYzMomQx/10ksZw0aFKQ7QgsvbH+L4f9hkdV3Rd51abBGgLN4Dv5HaSuSxK9A0c/HQhrMj6P1hJ4TsSbmg426+2Ng+Q7G0yZN2XL6WV7iSR1gz3YuzHs6LRrmEK72e3ooWp+o68yo/h66H6mw9VWIlLySSVSVA2wZUdjnnHfr6Qdhfa6nmnkIl+xf1TNnKz26iWcGxPMrWpFzQAiJfsSLQmlmNu0F3PtS/33rgJnn3uy++GPssGY9m9+jfTh09LHtCpEBCCiJvfnesFPWAnebJZ2tBlBtjpEvbDDBjgQ8/6JfvH0D1nI5sch/dPFQgQgVG7rc70XCBJ0UCeDlB5+XrooAtgZrQgLrY2ffLEHrx93cz6ZzJg+BaLxVa53BKFAK6lIGu2pHrVwz1NKKeuNl4t7s4EcQ1/683NiHI+QLl7tKjF4Vnj7hhr/7anHQn5JSAI2EjFx4h5VNdfNQphy1EFAYRWmLE2JjcI+D/IVLoflRkHnJC8XWPkyl2myesjh9FBSQCMlBVPknYBMqxfo1cvg6XKqQ=
