const OPEN_MODAL = "modal/OPEN_MODAL";
const OPEN_MODAL_FULL_SCREEN = "modal/OPEN_MODAL_FULL_SCREEN";
const CLOSE_MODAL = "modal/CLOSE_MODAL";
const CLOSE_ALL_MODAL = "modal/CLOSE_ALL_MODAL";

export default {
  OPEN_MODAL,
  OPEN_MODAL_FULL_SCREEN,
  CLOSE_MODAL,
  CLOSE_ALL_MODAL,
};
