const ENTITY = {
  ADD_COLLECTION: "entity/ADD_COLLECTION",
  UPDATE_ENTITY: "entity/UPDATE_ENTITY",
  REMOVE_ENTITY: "entity/REMOVE_ENTITY"
};

const ENTITY_REQUEST_STATUS = {
  GET_COLLECTION_START: "entity/REQUEST_STATUS/GET_COLLECTION_START",
  GET_COLLECTION_SUCCESS: "entity/REQUEST_STATUS/GET_COLLECTION_SUCCESS",
  GET_COLLECTION_ERROR: "entity/REQUEST_STATUS/GET_COLLECTION_ERROR"
};

const ENTITY_CLEAN_STATE = "entity/CLEAN_STATE";

export default {
  ENTITY,
  ENTITY_REQUEST_STATUS,
  ENTITY_CLEAN_STATE
};
