const ENTITY = {
  ADD_COLLECTION: "entity/ADD_COLLECTION",
  UPDATE_ENTITY: "entity/UPDATE_ENTITY",
};

const REQUEST_STATUS = {
  GET_COLLECTION_START: "entity/REQUEST_STATUS/GET_COLLECTION_START",
  GET_COLLECTION_SUCCESS: "entity/REQUEST_STATUS/GET_COLLECTION_SUCCESS",
  GET_COLLECTION_ERROR: "entity/REQUEST_STATUS/GET_COLLECTION_ERROR",
};

export default {
  ENTITY,
  REQUEST_STATUS,
};
